export const languages = [
  { name: 'JavaScript', icon: 'devicon-javascript-plain colored' },
  { name: 'TypeScript', icon: 'devicon-typescript-plain colored' },
  { name: 'Python', icon: 'devicon-python-plain colored' },
  { name: 'Java', icon: 'devicon-java-plain colored' },
  { name: 'HTML', icon: 'devicon-html5-plain colored' },
  { name: 'CSS', icon: 'devicon-css3-plain colored' },
  { name: 'C', icon: 'devicon-c-plain colored' },
  { name: 'Kotlin', icon: 'devicon-kotlin-plain colored' },
  { name: 'SQL', icon: 'devicon-mysql-plain colored' },
  //   { name: 'Cypher', icon: null },
  //   { name: 'JSON', icon: null },
  { name: 'SCSS', icon: 'devicon-sass-original colored' },
  { name: 'Dart', icon: 'devicon-dart-plain colored' },
  { name: 'LaTeX', icon: 'devicon-latex-original colored' },
]

export const technologies = [
  { name: 'Vue', icon: 'devicon-vuejs-plain colored' },
  { name: 'Svelte', icon: 'devicon-svelte-plain colored' },
  //   { name: 'React', icon: 'devicon-react-original colored' },
  { name: 'React Native', icon: 'devicon-react-original colored' },
  { name: 'Flutter', icon: 'devicon-flutter-plain colored' },
  //   { name: 'Tailwind CSS', icon: null }, // no official icon
  { name: 'Node.js', icon: 'devicon-nodejs-plain colored' },
  { name: 'Express', icon: 'devicon-express-original colored' },
  //   { name: 'pandas', icon: null },
  //   { name: 'matplotlib', icon: null },
  { name: 'MongoDB', icon: 'devicon-mongodb-plain colored' },
  { name: 'PostgreSQL', icon: 'devicon-postgresql-plain colored' },
  //   { name: 'Neo4j', icon: null },
  { name: 'Git', icon: 'devicon-git-plain colored' },
  { name: 'GitHub Pages', icon: 'devicon-github-original colored' },
  { name: 'Jupyter', icon: 'devicon-jupyter-plain colored' },
  { name: 'Visual Studio Code', icon: 'devicon-vscode-plain colored' },
  //   { name: 'Android Studio', icon: null },
  { name: 'Figma', icon: 'devicon-figma-plain colored' },
  { name: 'Docker', icon: 'devicon-docker-plain colored' },
  { name: 'Kubernetes', icon: 'devicon-kubernetes-plain colored' },
  { name: 'Vercel', icon: 'devicon-vercel-original colored' },
  { name: 'Cloudflare', icon: 'devicon-cloudflare-plain colored' },
  { name: 'Firebase', icon: 'devicon-firebase-plain colored' },
]
